### ISSUE TITLE
New build process to auto cache-bust files.

### ISSUE THREAD

**Issue by allanchau** [linzjs/linz#219]
## Expected behaviour

We should be able to run a build process and not have to worry about cache busting files when a change is made.

## Actual behaviour

A version query tag is required.

## Task

- [ ] Add rollup to linz as a dev dependency.
- [ ] Create a build process that builds a bundle file for each of the following paths
- common
- record save
- model save
- overview
- list view
- [ ] Make sure the files are in the format `file.[hash].js` and new hashes automatically clean up the previous hash.
- [ ] All assets should be contained inside of an `assets.json` file where we would refer to the file using the non-hashed version `{ test.js: "test.adsfadfgasdgadfsg.js" }`.
- [ ] Update all routes to use the new js files (common + 1 other).
- [ ] With this update, js scripts can be versioned using npm and bundled using rollup.
